name: Formatting

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        name: Lint
      - uses: astral-sh/ruff-action@v1
        name: Format
        with:
          args: "format --check"
